version: '3.8'

services:
    app:
        container_name: laravel_app
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - db

    web:
        container_name: nginx_server
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    db:
        container_name: mysql_db
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: rootpassword
        depends_on:
            - db
        networks:
            - laravel_network

volumes:
    dbdata:

networks:
    laravel_network:
        driver: bridge
